Parameters:
  BaseOperationEnvironment:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Environment
    Default: BaseOperationEnvironment
    ConstraintDescription: must specify nonprod, prod or test.
    MinLength: 1
  BaseOperationAppTagValues:
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
    Description: Application Tag Values 
    Default: 
    MinLength: 1 
  S3BucketName:
    Description: S3 Bucket for the BaseOperationApplication
    Type: String    

Resources:
 BaseOperationTechnicalAssessmentReport:
  Type: AWS::Glue::Job
  Properties:
   Name: Technical assessment 
   Command:
          Name: glueetl
          PythonVersion: 3
          ScriptLocation: !Join ['', ['s3://', !Ref S3BucketName , '.', !Ref edhPlatformEnvironment, '/deploy/bin/']]
   DefaultArguments:
          "--logsPath" : !Join ['', ['s3://', !Ref S3BucketName , '.', !Ref edhPlatformEnvironment, '/logs']]
          "--outputPath" : !Join ['', ['s3://', !Ref S3BucketName , '.', !Ref edhPlatformEnvironment, '/data/target']]
          "--job-bookmark-option": "job-bookmark-disable"
          "--TempDir" : !Join ['', ['s3://', !Ref S3BucketName , '.', !Ref edhPlatformEnvironment, '/temp']]
   GlueVersion: "2.0" 
   MaxRetries: 0
   Timeout: 2880
   LogUri: !Join ['', ['s3://', !Ref S3BucketName , '.', !Ref BaseOperationEnvironment, '/logs']]
   Description: "Base Operation Assessment Report"
   Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/"
   ExecutionProperty:
    MaxConcurrentRuns: 1  
   Tags: {
    "securitycenter": !Select [ 1, !Ref BaseOperationAppTagValues ],
    "threatapplication": !Select [ 0, !Ref BasseOperationAppTagValues ],
    "environment": !Ref BaseOperationEnvironment,
    "owner": !Select [ 2, !Ref BaseOperationAppTagValues ]
   }